project:
  type: website

website:
  title: "MiningAnalytics"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: KPI Dictionary
        href: kpis.qmd
      - text: Mine Analytics
        href: analytics.qmd

format:
  html:
    theme: cosmo
